pipeline {
	agent any
	tools {
		nodejs 'NodeJS'
	}
	environment {
		DOCKER_HUB_CREDENTIALS_ID = 'jen-dockerhub'
		DOCKER_HUB_REPO = 'shekthan5/shekthan5-nodeapp'
	}
	stages {
		stage('Checkout Github'){
			steps {
				git branch: 'main', credentialsId: 'jen-doc-git', url: 'https://github.com/shekar-thandava-1/jenkins.git'
			}
		}		
		stage('Install node dependencies'){
			steps {
				dir('node-app') {
					bat 'npm install'
				}
			}
		}
		stage('Test Code'){
			steps {
				dir('node-app') {
					bat 'npm test'
				}
			}
		}
		stage('Build Docker Image'){
			steps {
				dir('node-app') {
					script {
						dockerImage = docker.build("${DOCKER_HUB_REPO}:latest")
					}
				}
			}
		}
		stage('Push Image to DockerHub'){
			steps {
				dir('node-app') {
					script {
						docker.withRegistry('https://registry.hub.docker.com', "${DOCKER_HUB_CREDENTIALS_ID}"){
							dockerImage.push('latest')
						}
					}
				}
			}
		}
		stage('Deploy to Kubernetes'){
			steps {
				dir('node-app') {
					script{
						kubeconfig(caCertificate: 'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlRENDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTmpVM01qWTBPVGd3SGhjTk1qVXhNakUwTVRVek5EVTRXaGNOTXpVeE1qRXlNVFV6TkRVNApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTmpVM01qWTBPVGd3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSbC9NQS9GUnFkTHRZYnZYeW0vM2NUQTluZytxK0EzRG16MVJuM2dTSW4Kc2dQcDdoQWI0WUU4bXFuZnQ0ZWNJb1Z6cEFCYWZqbDZtSGljRnRkbW5sSzNvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVWlCUGx1ejd4cjM3WDBqL0dXS1U1CnI4MEd3UUF3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQU1kM1ZDSVlueUVJbTVRbWtMeXpFczVKQmdGTTFKSlEKZ2ZsYk02TlFMKzVnQWlFQWx2T1QrbDVQOGUvRWxsUVBQY1Mrc1BoS0VVVTdYM1RKWmpIS3ZadXg4ODA9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K', credentialsId: 'rancher-d-kubernetes-id', serverUrl: 'https://127.0.0.1:6443') {
						bat 'kubectl delete deployment.apps/node-app-deployment --ignore-not-found=true'
                        bat 'kubectl delete service/node-app-deployment --ignore-not-found=true'
						bat 'kubectl apply -f deployment.yaml'
                        bat 'kubectl expose deployment node-app-deployment --type=LoadBalancer --name=node-app-deployment --port=3000 --target-port=3000'
						}
					}
				}
		}
	}
  }
	post {
		success {
			echo 'Build&Deploy completed succesfully!'
		}
		failure {
			echo 'Build&Deploy failed. Check logs.'
		}
	}
}
